CONTRIBUTING.md, LICENSE.md, NOTICE.md, README.md
=> [nobug] add license/contributing/readme/notice files

pom.xml
Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>
=> Changed groupId and artifactId. Fixes #182

pom.xml
Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>
=> Changed groupId and artifactId. Fixes #182 (master)

pom.xml
=> adopt parent 1.0.5, add legal files to source bundle

CONTRIBUTING.md, NOTICE.md, README.md, pom.xml
=> #212: Change project name to Jakarta Persistence

spec/pom.xml, spec/src/main/asciidoc/license-efsl.adoc
=> fix status revmark, project version

README.md, spec/src/main/asciidoc/jakarta.persistence.adoc
=> fix scope statement

api/pom.xml, spec/pom.xml
=> adopt new parent, bump version to 3.0 and also fixes #240

api/pom.xml, api/src/main/java/module-info.java
=> add jpms descriptor

.travis.yml, api/copyright-exclude
=> set up travis

api/src/main/resources/jakarta/persistence/orm_3_0.xsd, api/src/main/resources/jakarta/persistence/persistence_3_0.xsd
=> fix hostname in schemas

api/src/main/resources/jakarta/persistence/orm_3_0.xsd, api/src/main/resources/jakarta/persistence/persistence_3_0.xsd
=> Remove duplicated copyright headers

api/pom.xml, spec/pom.xml
=> update projects to build on JDK 12+

api/src/main/java/jakarta/persistence/Temporal.java
Signed-off-by: bo he <qq111372757@gmail.com>
=> removing redundant parentheses.

CONTRIBUTING.md
=> #279: Update CONTRIBUTING.md for Specification Project's repositories

api/src/main/resources/jakarta/persistence/orm_3_0.xsd
=> #286: Update orm_3_0.xsd to refer to https://jakarta.ee/xml/ns/persistence/orm/orm_3_0.xsd

LICENSE.md
=> #284: Missing copy of the EDL/BSD 3-clause license in repo

spec/pom.xml, spec/src/main/asciidoc/ch01-introduction.adoc, spec/src/main/asciidoc/ch04-query-language.adoc, spec/src/main/asciidoc/ch08-entity-packaging.adoc, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc, spec/src/main/asciidoc/ch12-xml-or-mapping-descriptor.adoc, spec/src/main/asciidoc/jakarta.persistence-spec.adoc, spec/src/main/asciidoc/license-efsl.adoc
image location,
typos,
spec filename
=> fixed schemas,

api/pom.xml
=> Set project version to 3.1.0-SNAPSHOT

spec/src/main/asciidoc/ch04-query-language.adoc
Added single_valued_embeddable_object_field definition using Will's proposal in issue #307.
=> Added single_valued_embeddable_object_field definition to spec.

api/src/main/java/jakarta/persistence/GenerationType.java, api/src/main/resources/jakarta/persistence/orm_3_1.xsd, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch12-xml-or-mapping-descriptor.adoc
fix copyright years
follow-up on #319 
/cc @gavinking
=> fully absorb new orm schema version in the spec document,

.github/workflows/maven.yml, README.md, api/pom.xml
add status badges to the readme
=> add GH action to check PRs,

api/pom.xml
=> fix copyright year in javadoc footer,

api/src/main/java/jakarta/persistence/EntityNotFoundException.java, api/src/main/java/jakarta/persistence/NonUniqueResultException.java, api/src/main/java/jakarta/persistence/TransactionRequiredException.java
Allow nested exceptions on the few PersistenceExceptions subclasses that currently do not
=> Nested exceptions

api/src/main/java/jakarta/persistence/criteria/CriteriaBuilder.java
for #315 
Signed-off-by: Will Dazey <dazeydev.3@gmail.com>
=> Add support for Expressions as conditions in CriteriaBuilder CASE expressions

spec/pom.xml, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch01-introduction.adoc, spec/src/main/asciidoc/ch04-query-language.adoc, spec/src/main/asciidoc/ch07-entitymanagers-and-persistence-contexts.adoc, spec/src/main/asciidoc/ch12-xml-or-mapping-descriptor.adoc, spec/src/main/asciidoc/license-efsl.adoc
* fix build time warnings for spec document
* update the build of the spec project
=> update change log in the spec 

spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch04-query-language.adoc
=> Add || string concatenation operator

api/src/main/java/jakarta/persistence/Query.java, api/src/main/java/jakarta/persistence/StoredProcedureQuery.java, api/src/main/java/jakarta/persistence/TypedQuery.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch03-entity-operations.adoc
Adds the new method I proposed in this discussion: https://github.com/jakartaee/persistence/issues/298#issuecomment-736682475.
=> add Query.getSingleResultOrNull()

api/src/main/java/jakarta/persistence/criteria/Expression.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch06-criteria-api.adoc
=> add Expression.equalTo() and Expression.notEqualTo()

spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch02-entities.adoc, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc, spec/src/main/asciidoc/related-documents.adoc
=> add support for Instant and Year and clarify JDBC mappings for basic types

spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc
=> clarify the primary key types supported for each GenerationType

api/src/main/java/jakarta/persistence/criteria/CriteriaBuilder.java, spec/src/main/asciidoc/ch04-query-language.adoc, spec/src/main/asciidoc/ch06-criteria-api.adoc
=> Add left(), right(), and replace() functions to JPQL/criteria

api/src/main/java/jakarta/persistence/MapKeyTemporal.java, api/src/main/java/jakarta/persistence/Query.java, api/src/main/java/jakarta/persistence/StoredProcedureQuery.java, api/src/main/java/jakarta/persistence/Temporal.java, api/src/main/java/jakarta/persistence/TemporalType.java, api/src/main/java/jakarta/persistence/TypedQuery.java, spec/src/main/asciidoc/ch02-entities.adoc, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc
=> deprecate the use of java.util.Date and friends

api/src/main/java/jakarta/persistence/EntityManagerFactory.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch07-entitymanagers-and-persistence-contexts.adoc
See #410.
This one is just a rough draft.
=> Add EntityManagerFactory.runInTransaction()/callInTransaction()

api/src/main/java/jakarta/persistence/metamodel/Metamodel.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch05-metamodel-api.adoc
=> add Metamodel.entity(String)

spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc
=> add LocalDateTime and Instant to supported version types

api/src/main/java/jakarta/persistence/EnumType.java, api/src/main/java/jakarta/persistence/Enumerated.java, api/src/main/java/jakarta/persistence/EnumeratedValue.java, spec/src/main/asciidoc/ch02-entities.adoc, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc
=> introduce @EnumeratedValue and actually specify what ORDINAL and STRING mean

api/src/main/java/jakarta/persistence/metamodel/Bindable.java, spec/src/main/asciidoc/ch05-metamodel-api.adoc
=> clarify the semantics of Bindable.ENTITY_TYPE via javadoc

spec/src/main/asciidoc/ch03-entity-operations.adoc
=> specify that SEQUENCE, TABLE, UUID generated ids are available in @PrePersist

spec/src/main/asciidoc/ch03-entity-operations.adoc
tiny clarification for entity listeners
see #464
@lukasj for you, please review
=> light rewriting of section on lifecycle callback methods

api/src/main/java/jakarta/persistence/EntityManagerFactory.java, api/src/main/java/jakarta/persistence/PersistenceConfiguration.java, api/src/main/java/jakarta/persistence/PersistenceUnitTransactionType.java, api/src/main/java/jakarta/persistence/ValidationMode.java, api/src/main/java/jakarta/persistence/spi/PersistenceUnitTransactionType.java
and add `EntityManagerFactory.getTransactionType()`
see #477
=> deprecate PersistenceUnitTransactionType

api/src/main/java/jakarta/persistence/EntityManager.java, spec/src/main/asciidoc/ch03-entity-operations.adoc
=> Add getReference(detachedEntity) to EntityManager

api/src/main/java/jakarta/persistence/criteria/AbstractQuery.java, api/src/main/java/jakarta/persistence/criteria/CriteriaBuilder.java, api/src/main/java/jakarta/persistence/criteria/CriteriaQuery.java
=> add missing methods to AbstractQuery

spec/src/main/asciidoc/ch06-criteria-api.adoc
and add reference to `ManagedType` to static metamodel
see #459, #475
=> specify static string generation for metamodel classes

api/src/main/java/jakarta/persistence/criteria/Subquery.java
=> add missing covariant overrides to Subquery

api/src/main/java/jakarta/persistence/criteria/CommonAbstractCriteria.java, api/src/main/java/jakarta/persistence/criteria/From.java, api/src/main/java/jakarta/persistence/criteria/Join.java, api/src/main/java/jakarta/persistence/criteria/JoinType.java, spec/src/main/asciidoc/ch04-query-language.adoc, spec/src/main/asciidoc/ch06-criteria-api.adoc
=> add joins to entity types (range variables)

spec/src/main/asciidoc/ch04-query-language.adoc
=> very lightly rewrite section on input parameters

spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch06-criteria-api.adoc
=> #501: Define usage of javax.annotation.processing.Generated

api/src/main/java/jakarta/persistence/Timeout.java
=> eeek, constructor methods of Timeout must be static

api/src/main/java/jakarta/persistence/EntityManagerFactory.java, spec/src/main/asciidoc/ch07-entitymanagers-and-persistence-contexts.adoc
=> Add accessor for PU name to EntityManagerFactory

api/src/main/java/jakarta/persistence/EntityManager.java, api/src/main/java/jakarta/persistence/EntityManagerFactory.java
=> improvements to javadoc of EntityManager methods

README.md, api/pom.xml, spec/pom.xml
* updated parent
* updated pointers to the repository
* made jar reproducible
=> Project updates

spec/src/main/asciidoc/ch12-xml-or-mapping-descriptor.adoc
=> keep schema in spec in synch with the source

api/src/main/java/jakarta/persistence/Basic.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch02-entities.adoc
see https://github.com/jakartaee/persistence/issues/549
=> discourage Character[] and Byte[]

spec/src/main/asciidoc/ch02-entities.adoc
and move footnotes into main text
=> a clarification to field-level @Access

api/src/main/java/jakarta/persistence/MapsId.java
Explain that you have to assign it a value (language copied from spec).
=> add a note to javadoc of @MapsId

spec/src/main/asciidoc/ch03-entity-operations.adoc, spec/src/main/asciidoc/ch04-query-language.adoc
=> nail down semantics of collection-valued query parameters

api/src/main/resources/jakarta/persistence/persistence_3_1.xsd
Related to #377
This is in response to @lukasj suggestion in https://github.com/jakartaee/platform/pull/746 to include an extension point in the persistence schema rather than attempting to extend it externally.
=> Add an extension point for integration configuration concerns.

api/src/main/resources/jakarta/persistence/orm_3_2.xsd
=> fix maxOccurs for version element in orm.xml

spec/src/main/asciidoc/ch04-query-language.adoc
also clarify the meaning of `result_variable`
see #597
=> allow scalar expressions in 'order by'

spec/src/main/asciidoc/ch04-query-language.adoc
this has been bugging me for a long time
=> consistently use monospace font in ch4

spec/src/main/asciidoc/ch03-entity-operations.adoc, spec/src/main/asciidoc/ch06-criteria-api.adoc, spec/src/main/asciidoc/ch07-entitymanagers-and-persistence-contexts.adoc, spec/src/main/asciidoc/ch09-container-provider-contracts.adoc, spec/src/main/asciidoc/ch10-metadata-annotations.adoc, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc
Found a few more things to fix.
=> more work on correct use of monospace font

spec/src/main/asciidoc/ch03-entity-operations.adoc
I accidentally monospaced a regular word
=> two very minor formatting changes

api/src/main/java/jakarta/persistence/MapKey.java, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc
thanks @pzygielo for the catch
=> fix to spec of #684

api/src/main/java/jakarta/persistence/PersistenceConfiguration.java
=> errata: fix two property names in PersistenceConfiguration

api/src/main/java/jakarta/persistence/Entity.java, spec/src/main/asciidoc/ch04-query-language.adoc, spec/src/main/asciidoc/ch10-metadata-annotations.adoc, spec/src/main/asciidoc/ch12-xml-or-mapping-descriptor.adoc
=> specify that entity names must be legal Java identifiers
