api/pom.xml
Signed-off-by: Scott Marlow <smarlow@redhat.com>
> cat api/target/classes/META-INF/MANIFEST.MF
> Manifest-Version: 1.0
> Automatic-Module-Name: jakarta.persistence
> Bnd-LastModified: 1580494494199
> Build-Jdk: 1.8.0_181
> Built-By: smarlow
> Bundle-Description: Jakarta Persistence 2.2 API jar
> Bundle-DocURL: https://www.eclipse.org
> Bundle-License: http://www.eclipse.org/legal/epl-2.0, http://www.eclipse
>  .org/org/documents/edl-v10.php
> Bundle-ManifestVersion: 2
> Bundle-Name: Jakarta Persistence API jar
> Bundle-SymbolicName: jakarta.persistence-api
> Bundle-Vendor: Eclipse Foundation
> Bundle-Version: 2.2.3
> Created-By: Apache Maven Bundle Plugin
> Export-Package: jakarta.persistence;uses:="jakarta.persistence.criteria,
> …
=> change module name to jakarta.persistence

api/src/main/resources/jakarta/persistence/orm_3_0.xsd, api/src/main/resources/jakarta/persistence/persistence_3_0.xsd
version 3.0 of persistence.xsd and orm.xsd. The only difference from previous version is the definition of target namespace, which is now:
`https://xmlns.jakarta.ee/xml/ns/persistence` for `persistence.xsd`
`https://xmlns.jakarta.ee/xml/ns/persistence/orm` for `orm.xsd`
=> new schema versions

.gitignore, spec/pom.xml
After fetching the latest version of the master, generating asciidocs stopped working. This commit fixes that by updating the asciidoctorj version.
=> Fixed asciidoc error by updating the asciidoctorj version

api/src/main/java/jakarta/persistence/metamodel/ListAttribute.java
=> javax.util.List typo in Javadoc of ListAttribute

spec/src/main/asciidoc/related-documents.adoc
I updated references to point to the eclipse project instead of jcp pages. For some of them that were referencing an old version of specs, I just changed them to just the spec name and spec version (suggested in the "Cleanup Steps" of the [Converting Java EE Specification Documents to Jakarta EE.
](https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc)
I'm not sure about the number 3, "JDBC 4.2 Specification". It's not an eclipse-ee4j project, so I didn't change the URL.
=> Updated references to point to Jakarta project pages

spec/src/main/asciidoc/ch08-entity-packaging.adoc, spec/src/main/asciidoc/ch09-container-provider-contracts.adoc, spec/src/main/asciidoc/ch12-xml-or-mapping-descriptor.adoc, spec/src/main/asciidoc/related-documents.adoc
With relaxed overall backwards compatibility related requirements of Jakarta EE 9, I'd like to remove explicit requirements wrt supporting older/Java EE schemas defined in the persistence spec
=> Drop references to older/Java EE versions of the schema from the spec

api/src/main/java/jakarta/persistence/EntityManager.java, api/src/main/java/jakarta/persistence/EntityManagerFactory.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch03-entity-operations.adoc, spec/src/main/asciidoc/ch07-entitymanagers-and-persistence-contexts.adoc
=> #77: EntityManager(Factory) should implement AutoCloseable

spec/src/main/asciidoc/ch04-query-language.adoc
Proposal for addition of `EXTRACT()` to JPAQL.
I made the following choices, which should be reviewed:
- I defined `EXTRACT` as a (new) keyword for consistency with how other function names are defined. (I don't like that the JPA spec treats function names as keywords, FTR.)
- But I defined the field types as *identifiers*, because I didn't want to add lots of new keywords, and because I wanted to make it easy to extend this list in either (a) future spec revisions, and (b) vendor extensions to the spec.
- (For now) I included only the field types `YEAR`, `QUARTER`, `MONTH`, `WEEK`, `DAY`, `HOUR`, `MINUTE`, `SECOND`, `DATE`, `TIME`. 
Note that our product&mdash;and some databases&mdash;support more field types than these, but I've limited the functionality to the field types that are …
=> specify JPAQL EXTRACT function

spec/src/main/asciidoc/ch02-entities.adoc
Based on my proposal in Issue #120.
=> Added definition of Basic type

api/src/main/java/jakarta/persistence/spi/ClassTransformer.java, api/src/main/java/jakarta/persistence/spi/PersistenceUnitInfo.java, api/src/main/java/jakarta/persistence/spi/Transformer.java, api/src/main/java/jakarta/persistence/spi/TransformerException.java, api/src/main/java/module-info.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch09-container-provider-contracts.adoc
Making dependency on `java.instrument`/`java.lang.instrument.IllegalClassFormatException` optional by introducing new `Transformer` interface superseding current `ClassTransformer` interface, which has been deprecated. Specification has been updated to make implementation of  `ClassTransformer` by the persistence provider explicitly optional.
=> #264: avoid transitive dependency on java.instrument

api/pom.xml
Apart from updating build plugins, this moves binary level to SE 11 (and drops 8/9 compatibility) as is recommended by the Platform. If there is a reason to NOT move the binary level of the api artifact to SE 11 and keep it at 8/9, speak up, please, and I'll update related part of the change. I'd like to merge this change by Thu Dec 9. Thx
=> bump src level to 11, update build plugins

spec/src/main/asciidoc/ch03-entity-operations.adoc
fixes #238
Signed-off-by: Will Dazey <dazeydev.3@gmail.com>
=> Issue 238: Clarify mixing input parameter types for queries

api/src/main/java/jakarta/persistence/GenerationType.java, api/src/main/resources/jakarta/persistence/orm_3_1.xsd, spec/src/main/asciidoc/ch02-entities.adoc, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc
Draft support for `UUID`.
See #151 and #152.
Thoughts?
=> spec UUID support

spec/src/main/asciidoc/ch04-query-language.adoc
Signed-off-by: Tomas Kraus <tomas.kraus@oracle.com>
=> Fixed JPAQL EXTRACT function specification.

api/src/main/java/jakarta/persistence/criteria/CriteriaBuilder.java, spec/src/main/asciidoc/ch04-query-language.adoc, spec/src/main/asciidoc/ch06-criteria-api.adoc
The current wording is very difficult for non-native speakers to understand, "located" being almost a synonym for "searched", and was apparently even misread by the person who wrote `CriteriaBuilder`, since `CriteriaBuilder.locate()` gets the parameters in the "wrong" order.
I have (a bit laboriously) clarified the semantics of the JPQL function `locate()`, and added a warning to the Javadoc of `CriteriaBuilder.locate()`.
=> clarify the parameter order of the locate() function

spec/src/main/asciidoc/ch04-query-language.adoc
`EXTRACT(SECOND...)` should return a floating point value because truncating fractional seconds isn't useful.
=> fix the definition of EXTRACT(SECOND...) 

api/src/main/java/jakarta/persistence/criteria/CriteriaBuilder.java, spec/src/main/asciidoc/ch04-query-language.adoc
This finally puts support for the `LocalDate`, `LocalTime`, and `LocalDateTime` types defined by `java.time` on an equal footing to support for the bad old `Date`,`Time`,`Timestamp` classes in `java.sql`.
It also clarifies the types of `current_date` and friends, which were left undefined until now, but which were interpreted by implementations to mean the `java.sql` types.
=> introduce local date/time special functions

api/src/main/java/jakarta/persistence/criteria/CriteriaBuilder.java, spec/src/main/asciidoc/ch04-query-language.adoc
This adds `sign()`, `exp()`, `power()`, `ln()`, `round()`, `floor()`, `ceiling()` to the list of functions portably supported in JPQL. Each of these functions (or something very similar) is available on essentially every SQL database, and are needed in any language which is intended to be used for any sort of nontrivial data analysis. In particular, the natural logarithm and functions for rounding are pretty essential.
I have (against my own preference) *not* included trigonometric functions.
=> introduce several "missing" numeric functions

api/src/main/java/jakarta/persistence/AttributeOverrides.java
Add missing `name` attribute to the example codes in AttributeOverrides javadoc.
=> Fixes the example codes in AttributeOverrides javadoc

api/src/main/java/jakarta/persistence/GeneratedValue.java, api/src/main/java/jakarta/persistence/SequenceGenerator.java, api/src/main/java/jakarta/persistence/TableGenerator.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc, spec/src/main/asciidoc/ch12-xml-or-mapping-descriptor.adoc
=> Make the name member of @XxxxGenerator annotations optional

api/src/main/java/jakarta/persistence/criteria/CriteriaBuilder.java, api/src/main/java/jakarta/persistence/criteria/CriteriaQuery.java, spec/src/main/asciidoc/appendixes.adoc
=> overload where(), having(), and(), and or() to accept List<Predicate>

api/src/main/java/jakarta/persistence/criteria/CriteriaBuilder.java, api/src/main/java/jakarta/persistence/criteria/Nulls.java, api/src/main/java/jakarta/persistence/criteria/Order.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch04-query-language.adoc
=> add support for 'nulls first' and 'nulls last' in queries

spec/src/main/asciidoc/ch04-query-language.adoc
see #423.
This proposal clarifies the types assigned to numeric literals, and allows `BigInteger` and `BigDecimal` literals to be specified using the suffix `bi` or `bd` respectively.
=> nail down semantics of numeric literals and add 'bi' and 'bd' suffixes

api/src/main/java/jakarta/persistence/criteria/Expression.java, spec/src/main/asciidoc/ch04-query-language.adoc
=> add CAST() function to JPQL + Expression.cast() method

api/src/main/java/jakarta/persistence/EntityGraph.java, api/src/main/java/jakarta/persistence/Graph.java, api/src/main/java/jakarta/persistence/Subgraph.java, spec/src/main/asciidoc/ch03-entity-operations.adoc
=> fix signatures of operations of entity graphs

api/src/main/java/jakarta/persistence/PersistenceUnitUtil.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch07-entitymanagers-and-persistence-contexts.adoc
=> add new operations to PersistenceUnitUtil

api/src/main/java/jakarta/persistence/CacheRetrieveMode.java, api/src/main/java/jakarta/persistence/CacheStoreMode.java, api/src/main/java/jakarta/persistence/EntityGraph.java, api/src/main/java/jakarta/persistence/EntityManager.java, api/src/main/java/jakarta/persistence/FindOption.java, api/src/main/java/jakarta/persistence/Graph.java, api/src/main/java/jakarta/persistence/LockModeType.java, api/src/main/java/jakarta/persistence/LockOption.java, api/src/main/java/jakarta/persistence/NamedSubgraph.java, api/src/main/java/jakarta/persistence/PessimisticLockScope.java, api/src/main/java/jakarta/persistence/Query.java, api/src/main/java/jakarta/persistence/RefreshOption.java, api/src/main/java/jakarta/persistence/StoredProcedureQuery.java, api/src/main/java/jakarta/persistence/Timeout.java, api/src/main/java/jakarta/persistence/TypedQuery.java, spec/src/main/asciidoc/ch03-entity-operations.adoc
Introduces:
- `FindOption` interface and new overloads of `EM.find()`
- `RefreshOption` interface and new overloads of `EM.refresh()`
- `LockOption` interface and new overloads of `EM.lock()`
- `Graph.removeAttributeNode()`
- `setCacheStoreMode()`/`setCacheRetreiveMode()` on `EntityManager` and `Query`
see #383 and #65. (Also #64.)
=> introduce FindOption interface and new overloads of EM.find()

api/src/main/java/jakarta/persistence/EntityManagerFactory.java, api/src/main/java/jakarta/persistence/SchemaManager.java, api/src/main/java/jakarta/persistence/SchemaValidationException.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch07-entitymanagers-and-persistence-contexts.adoc, spec/src/main/asciidoc/ch08-entity-packaging.adoc, spec/src/main/asciidoc/ch09-container-provider-contracts.adoc
This is a first draft proposal, looking for feedback!
see #399, #68, and #53
=> add SchemaManager

spec/src/main/asciidoc/ch04-query-language.adoc
and clarify rules around case-sensitivity
see #30
=> put entity names and identification vars in distinct namespaces

api/src/main/java/jakarta/persistence/ConnectionConsumer.java, api/src/main/java/jakarta/persistence/ConnectionFunction.java, api/src/main/java/jakarta/persistence/EntityManager.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch03-entity-operations.adoc
=> add EntityManager.runWithConnection()/callWithConnection()

api/src/main/java/jakarta/persistence/PersistenceUnitUtil.java, spec/src/main/asciidoc/ch07-entitymanagers-and-persistence-contexts.adoc
=> add PersistenceUnitUtil.getVersion()

api/src/main/java/jakarta/persistence/ColumnResult.java, api/src/main/java/jakarta/persistence/ConstructorResult.java, api/src/main/java/jakarta/persistence/EntityResult.java, api/src/main/java/jakarta/persistence/FieldResult.java, api/src/main/java/jakarta/persistence/NamedNativeQuery.java, spec/src/main/asciidoc/ch10-metadata-annotations.adoc
and add lockMode to `@EntityResult`.
see #471, #472
=> allow result set mappings to be embedded directly in @NamedNativeQuery

api/src/main/java/jakarta/persistence/Persistence.java, api/src/main/java/jakarta/persistence/PersistenceConfiguration.java, api/src/main/java/jakarta/persistence/PersistenceTransactionType.java, api/src/main/java/jakarta/persistence/spi/PersistenceProvider.java, spec/src/main/asciidoc/ch07-entitymanagers-and-persistence-contexts.adoc, spec/src/main/asciidoc/ch08-entity-packaging.adoc, spec/src/main/asciidoc/ch09-container-provider-contracts.adoc
=> add PersistenceConfiguration

api/src/main/java/jakarta/persistence/ConnectionConsumer.java, api/src/main/java/jakarta/persistence/ConnectionFunction.java, api/src/main/java/jakarta/persistence/EntityManager.java, spec/src/main/asciidoc/ch03-entity-operations.adoc
makes the connection type generic
see #483
=> eliminate dependence on JDBC from runWithConnection()

spec/src/main/asciidoc/ch04-query-language.adoc
I missed this when I backed out this functionality.
@lukasj sorry, another oversight
=> replace right/full join with a footnote

api/src/main/java/jakarta/persistence/Cache.java, api/src/main/java/jakarta/persistence/Convert.java, api/src/main/java/jakarta/persistence/ElementCollection.java, api/src/main/java/jakarta/persistence/EntityManager.java, api/src/main/java/jakarta/persistence/EntityManagerFactory.java, api/src/main/java/jakarta/persistence/IdClass.java, api/src/main/java/jakarta/persistence/ManyToMany.java, api/src/main/java/jakarta/persistence/ManyToOne.java, api/src/main/java/jakarta/persistence/MapKeyClass.java, api/src/main/java/jakarta/persistence/OneToMany.java, api/src/main/java/jakarta/persistence/OneToOne.java, api/src/main/java/jakarta/persistence/Persistence.java, api/src/main/java/jakarta/persistence/StoredProcedureParameter.java, api/src/main/java/jakarta/persistence/StoredProcedureQuery.java, api/src/main/java/jakarta/persistence/spi/PersistenceProvider.java
=> remove raw types from APIs and fix typesafety of @Convert annotation

api/src/main/java/jakarta/persistence/Persistence.java
I briefly checked the TCK and found no usages of deprecated fields - @scottmarlow or @gurunrao / @alwin-joseph can you doublecheck this is fine from TCK's point of view, please?
fixes #498
=> Mark deprecated fields in Persistence for removal

api/src/main/java/jakarta/persistence/spi/PersistenceUnitInfo.java
@gavinking we've missed part in PersistenceUnitInfo; the name of the new method is long, but do you have better idea?
fixes #477
=> finish deprecation of spi.PersistenceUnitTransactionType

api/src/main/java/jakarta/persistence/SequenceGenerator.java, api/src/main/java/jakarta/persistence/SequenceGenerators.java, api/src/main/java/jakarta/persistence/TableGenerator.java, api/src/main/java/jakarta/persistence/TableGenerators.java, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc, spec/src/main/asciidoc/ch12-xml-or-mapping-descriptor.adoc
These two commits:
1. fix an oversight in #406, where the name defaulting for `@GeneratedValue` was defined only in Javadoc but not in the spec, and
2. adds package-level `@SequenceGenerator` and `@TableGenerator` annotations, as proposed in #511.
=> package-level @SequenceGenerator and @TableGenerator

api/src/main/java/jakarta/persistence/criteria/CriteriaBuilder.java, api/src/main/java/jakarta/persistence/criteria/CriteriaQuery.java, spec/src/main/asciidoc/appendixes.adoc, spec/src/main/asciidoc/ch06-criteria-api.adoc
There are two commits here:
1. adds overloads of `array()`, `tuple()` accepting `List` to `CriteriaBuilder`, and
2. deprecates `multiselect()` because it's not typesafe.
=> deprecate CriteriaQuery.multiselect and add overloads of array(), tuple()

spec/src/main/asciidoc/ch02-entities.adoc, spec/src/main/asciidoc/ch03-entity-operations.adoc, spec/src/main/asciidoc/ch10-metadata-annotations.adoc, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc
- Actually define what a converter target type is!
- Clarify what happens with a plain `@Convert` with no `converter` and no `disableConversion` ... it was vaguely implied by the javadoc that this applies a non-auto-apply converter, but this was contradicted by a line in the spec saying that the behavior is undefined.
- Make it clear that the "target type" may be any arbitrary Java type, but that the converted type must be a basic type.
- Properly define all cases involving element collections.
see #509
=> nail down holes in the semantics of @Converter/@Convert

api/src/main/java/jakarta/persistence/Query.java, api/src/main/java/jakarta/persistence/TypedQuery.java
=> minor clarification to what is returned by getResultList()

api/src/main/java/jakarta/persistence/EntityManager.java
preparing the way for #52 (which we won't do until JPA 4)
Change suggested by @lukasj in response to problem raised by @sebersole.
=> slight adjustment to signature of EntityManager.createNativeQuery()

api/src/main/java/jakarta/persistence/Graph.java
@sebersole has requested the attached changes to the `Graph` interface
@lukasj WDYT?
There are two related changes here:
- make `addAttributeNode()` return the `AttributeNode`
- add `getOrAddAttributeNode()` and `getAttributeNode()`
=> improvements to Graph operations for handling AttributeNodes

api/src/main/java/jakarta/persistence/EntityManager.java, api/src/main/java/jakarta/persistence/EntityManagerFactory.java, api/src/main/java/jakarta/persistence/NamedEntityGraph.java, api/src/main/java/jakarta/persistence/NamedNativeQuery.java, api/src/main/java/jakarta/persistence/NamedQuery.java, api/src/main/java/jakarta/persistence/TypedQueryReference.java, spec/src/main/asciidoc/ch06-criteria-api.adoc, spec/src/main/asciidoc/ch10-metadata-annotations.adoc
Introduces `NamedQueryReference` and:
```java
interface EntityManagerFactory {
...
<R> Map<String, NamedQueryReference<R>> getNamedQueries(Class<R> resultType);
<E> Map<String, EntityGraph<? extends E>> getNamedEntityGraphs(Class<E> entityType);
}
```
```java
interface EntityManager {
...
<R> TypedQuery<R> createNamedQuery(NamedQueryReference<R> reference);
}
```
as proposed in #505.
Also adds typesafe references to named queries and named entity graphs to the canonical metamodel, enabling typesafe code like:
```java
@NamedEntityGraph(name = "withAuthors", ... )
@Entity
class Book { ... }
Book book = em.find(Book_._withAuthors, bookId);
```
and:
```java
@NamedQuery(name = "byTitle", ... )
@Entity
class Book { ... }
List<Book> books = 
em.createNamedQuery(Book_._byTitle_)
.setParameter(1, …
```
=> factory-level access to named queries and named entity graphs

spec/src/main/asciidoc/ch02-entities.adoc, spec/src/main/asciidoc/ch03-entity-operations.adoc, spec/src/main/asciidoc/ch04-query-language.adoc, spec/src/main/asciidoc/ch07-entitymanagers-and-persistence-contexts.adoc, spec/src/main/asciidoc/ch08-entity-packaging.adoc, spec/src/main/asciidoc/ch11-metadata-for-or-mapping.adoc
Generally, a code example should not be declared in its own section, but should rather occur directly in the section of the spec defining the stuff it's an example of. Here, I've cleaned up most of the instances which violated this principle.
=> examples should not have their own section

spec/src/main/asciidoc/ch02-entities.adoc
Make use of `PersistentAttributeType` to make clear that an entity attribute can't be more than one kind of thing.
=> introduce Persistent Attribute Type section

spec/src/main/asciidoc/ch02-entities.adoc
The list of allowed attribute types was in the wrong section, and also a duplicated material from the section on basic types.
=> move and rewrite list of allowed attribute types

spec/src/main/asciidoc/ch04-query-language.adoc
I messed up and used a syntax that breaks asciidoctor PDF (it works in HTML output).
=> fix broken emdashes

spec/src/main/asciidoc/ch05-metamodel-api.adoc
fixes #589
this should also handle the case where the name of a named thing is with a dot (ie `Employee.findAll`)
=> #589: avoid collisions in metamodel's variables

spec/src/main/asciidoc/ch04-query-language.adoc
Eeeeek, apologies @lukasj I messed this up. Of course I *totally* intended for `entity_id_or_version_function` to be a `scalar_expression` and I could have sworn I wrote that down!
=> allow id() and version() in scalar_expression rule

api/src/main/java/jakarta/persistence/Column.java, api/src/main/java/jakarta/persistence/EntityManager.java, api/src/main/java/jakarta/persistence/EntityManagerFactory.java, api/src/main/java/jakarta/persistence/Query.java, api/src/main/java/jakarta/persistence/TypedQuery.java, api/src/main/java/jakarta/persistence/TypedQueryReference.java, spec/src/main/asciidoc/appA-revision-history.adoc
1. add missing `@since` annotations
2. mention `TypedQueryReference` in changelog
=> Two minor things for 3.2

spec/src/main/asciidoc/ch03-entity-operations.adoc
After the spec reorg, this position of this admonition made no sense with respect to the flow of the text.
=> move a NOTE to a much more sensible location
